### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by player52rus** [q1701/build-checkinstall#1]
Help please, when executing ./run error crashes:

Installed:
   patch.x86_64 0: 2.7.1-8.el7

Complete!
patching file installwatch / Makefile
patching file Makefile
can not find file to patch at input line 18
Perhaps you used the wrong -p or -strip option?
The text leading up to this was:
--------------------------
| diff --git a / checkinstall b / checkinstall
| index 978360f..a3917a4 100755
| --- a / checkinstall
| +++ b / checkinstall
--------------------------
File to patch:

and all ... I can not do anything ...
Tell me please how to solve?

CentOS Linux release 7.3.1611 (Core)
Linux test 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by q1701** [comment]
Some patches were too old for the latest version of checkinstall.
I have fixed them.
Please try again!
