### ISSUE TITLE
fatal error while executing run script

### ISSUE THREAD

**Issue by javabeanz** [q1701/build-checkinstall#2]
fatal: unable to access 'http://checkinstall.izto.org/checkinstall.git/': Failed connect to checkinstall.izto.org:80; Connection timed out

git repo had moved ?

**Comment by q1701** [comment]
I can run the script successfully.
Could you try again?
Or, Is your network needs a http proxy?

**Comment by javabeanz** [comment]
tried again, without any problem. Don't know what's changed. Sorry for this inconvenience.
